export const RESERVATION_MAKE_PREORDER = 'RESERVATION_MAKE_PREORDER';

export const RESERVATION_ADD_PREORDER_ITEM = 'RESERVATION_ADD_PREORDER_ITEM';

export const RESERVATION_DATE_TIME = 'RESERVATION_DATE_TIME';

export const RESERVATION_INFO = 'RESERVATION_INFO';

export const RESERVATION_CLEAR_DATA = 'RESERVATION_CLEAR_DATA';
