export const RESTAURANT_INFO = 'RESTAURANT_INFO';

export const RESTAURANT_INFO_REQUEST = 'RESTAURANT_INFO_REQUEST';

export const RESTAURANT_INFO_ERROR = 'RESTAURANT_INFO_ERROR';

export const RESTAURANT_NA = 'RESTAURANT_NA';

export const RESTAURANT_EDIT_REQUEST = 'RESTAURANT_EDIT_REQUEST';

export const RESTAURANT_EDIT = 'RESTAURANT_EDIT';

export const RESTAURANT_EDIT_ERROR = 'RESTAURANT_EDIT_ERROR';

export const RESTAURANT_LOGO = 'RESTAURANT_LOGO';

export const RESTAURANT_RESET = 'RESTAURANT_RESET';

export const RESTAURANT_CREATE_ERROR = 'RESTAURANT_CREATE_ERROR';

export const RESTAURANT_CREATE_REQUEST = 'RESTAURANT_CREATE_REQUEST';

export const RESTAURANT_CREATE = 'RESTAURANT_CREATE';
