# Generated by Django 3.2.9 on 2021-12-15 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_auto_20211215_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='cancelled', max_length=10),
            preserve_default=False,
        ),
    ]
