# Generated by Django 3.2.9 on 2021-12-17 20:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0019_auto_20211215_1901'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverOrderStatus',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(default='available', max_length=10)),
                ('total_order', models.IntegerField(default=0)),
                ('current_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.order')),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
