# Generated by Django 3.2.9 on 2021-12-27 20:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0020_driverorderstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('num_of_pax', models.IntegerField()),
                ('status', models.CharField(default='active', max_length=16)),
                ('reservedDateTime', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PreOrder',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.product')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.reservation')),
            ],
        ),
    ]
