# Generated by Django 3.2.9 on 2021-12-27 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_preorder_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='pre_order',
            field=models.BooleanField(default=False),
        ),
    ]
