# Generated by Django 3.2.9 on 2022-01-06 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_reservation_pre_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverorderstatus',
            name='last_assigned',
            field=models.BooleanField(default=False),
        ),
    ]
