# Generated by Django 3.2.9 on 2022-01-10 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_driverorderstatus_active_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverorderstatus',
            name='current_order',
        ),
    ]
