# Generated by Django 3.2.9 on 2022-01-10 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0026_remove_driverorderstatus_current_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='my_restaurant', max_length=128)),
                ('description', models.TextField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, default='/sample.jpg', null=True, upload_to='')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantReview',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('comments', models.TextField(blank=True, null=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='Promos',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=16)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=4)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.product')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=32)),
                ('postal_code', models.CharField(max_length=8)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.restaurant')),
            ],
        ),
    ]
