# Generated by Django 3.2.9 on 2022-01-10 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_auto_20220110_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='contact_number',
            field=models.CharField(default='', max_length=16),
            preserve_default=False,
        ),
    ]
