# Generated by Django 3.2.9 on 2022-01-11 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_featureproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='promos',
            name='code',
            field=models.CharField(default='', max_length=16),
            preserve_default=False,
        ),
    ]
