# Generated by Django 3.2.9 on 2022-01-15 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_promos_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featureproduct',
            name='priority',
        ),
    ]
