# Generated by Django 3.2.9 on 2022-01-18 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_promos_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promos',
            name='amount',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
    ]
