# Generated by Django 3.2.9 on 2022-01-19 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0040_restaurantreview_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantreview',
            name='comments',
        ),
        migrations.AddField(
            model_name='restaurantreview',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
