# Generated by Django 3.2.9 on 2022-01-23 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0041_auto_20220119_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='restaurant',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='base.restaurant'),
            preserve_default=False,
        ),
    ]
