# Generated by Django 3.2.9 on 2022-01-26 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0042_reservation_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='preorder',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='preorder',
            name='qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='preorder',
            name='totalPrice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
