# Generated by Django 3.2.9 on 2022-02-01 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0044_remove_preorder_totalprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverorderstatus',
            name='total_delivery',
            field=models.IntegerField(default=0),
        ),
    ]
