# Generated by Django 3.2.9 on 2022-02-03 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0045_driverorderstatus_total_delivery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Support',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=24)),
                ('type', models.CharField(max_length=16)),
                ('headline', models.TextField()),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
