# Generated by Django 3.2.9 on 2022-02-04 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0046_support'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempURL',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=24)),
                ('token', models.CharField(max_length=512)),
                ('expire_time', models.DateTimeField()),
                ('status', models.CharField(default='new', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='support',
            name='email',
            field=models.CharField(max_length=64),
        ),
    ]
